### ISSUE TITLE
Feature: Bundles Compatibility 

### ISSUE THREAD

**Issue by LysanderTron** [saturn-volv/WITL#2]
Compasses working to give waypoints whilst in bundles would be nice, carrying around 10 compasses fills up a lot of your inventory but I dont want to resort to F3 for the sake of immersion, bundles working would be amazing!

**Comment by saturn-volv** [comment]
I actually planned to have this functionality but completely forgot to implement it! I'll code it in now :D

**Comment by saturn-volv** [comment]
[I finished it lol](https://modrinth.com/mod/where-is-that-lodestone/version/alpha-v0.1.3)
